package hvqzao.flow.ui;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;

public class Editor extends javax.swing.JPanel implements IEditor {

    private DefaultCaret caret;
    private IExtensionHelpers helpers;
    
    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
    }

    @Override
    public boolean hasFocus() {
        return editor.hasFocus();
    }
    
    @Override
    public void customizeUiComponent(final IBurpExtenderCallbacks callbacks) {
        helpers = callbacks.getHelpers();
        callbacks.customizeUiComponent(editor);
        callbacks.customizeUiComponent(prev);
        callbacks.customizeUiComponent(next);
        callbacks.customizeUiComponent(search);
    }
    
    @Override
    public void setText(byte[] message) {
        caret = (DefaultCaret) editor.getCaret();
        caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        if (message != null) {
            editor.setText(helpers.bytesToString(message));
        }
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        //request.setEditable(false);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        search = new javax.swing.JTextField();

        editor.setColumns(20);
        editor.setRows(5);
        jScrollPane5.setViewportView(editor);

        prev.setText("<");
        prev.setEnabled(false);

        next.setText(">");
        next.setEnabled(false);

        search.setToolTipText("");
        search.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(prev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prev)
                    .addComponent(next)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea editor;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton next;
    private javax.swing.JButton prev;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextArea getEditor() {
        return editor;
    }
}
